[package]
name = "encoding-demo"
version = "0.1.0"
authors = ["chychy37 <271163113@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = ""
hex = ""
